version: "3.8"

services:
  golang-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: golang-server
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - url-shorten-network
  database:
    container_name: url-shortener-database
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      # - ./docker/postgres-data/:/var/lib/postgresql/data
      - url-shorten-database:/var/lib/postgres
      - ./docker/postgres-data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: url-database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 5433:5432
    networks:
      - url-shorten-network

networks:
  url-shorten-network:
    driver: bridge

volumes:
  url-shorten-database:
    driver: local
